### ISSUE TITLE
Remove "Bot" from Username

### ISSUE THREAD

**Issue by paultibbetts** [danielsamuels/sscaas#22]
Hey @danielsamuels, 

Thanks for making (and hosting) SSCaaS, we've only been using it a few hours and it's already proved itself useful.

<img width="298" alt="screen shot 2016-06-08 at 12 00 19" src="https://cloud.githubusercontent.com/assets/2053583/15892248/a5652f36-2d70-11e6-9263-e72bb0d3211a.png">

Would you be open to a PR removing the Bot from the usernames as Slack automatically adds it?

Thanks,

Paul

**Comment by danielsamuels** [comment]
Makes sense, happy to accept a PR on that.
